DROP DATABASE IF EXISTS kbc_game;
CREATE DATABASE kbc_game CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kbc_game;

CREATE TABLE users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(100) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL
) ENGINE=InnoDB;

CREATE TABLE questions (
    question_id INT PRIMARY KEY AUTO_INCREMENT,
    question_text VARCHAR(500) NOT NULL,
    category VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE options (
    option_id INT PRIMARY KEY AUTO_INCREMENT,
    question_id INT NOT NULL,
    option_label CHAR(1) NOT NULL,
    option_text VARCHAR(300) NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_options_question FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE,
    CONSTRAINT uq_question_option_label UNIQUE (question_id, option_label)
) ENGINE=InnoDB;

CREATE TABLE user_interactions (
    interaction_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    question_id INT NOT NULL,
    selected_option_id INT NULL,
    score INT NOT NULL DEFAULT 0,
    lifelines_used VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    question_number INT NOT NULL,
    time_taken_seconds INT NOT NULL,
    answered_at DATETIME NOT NULL,
    CONSTRAINT fk_interactions_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_interactions_question FOREIGN KEY (question_id) REFERENCES questions(question_id),
    CONSTRAINT fk_interactions_option FOREIGN KEY (selected_option_id) REFERENCES options(option_id)
) ENGINE=InnoDB;

INSERT INTO questions (question_text, category) VALUES
('In object-oriented programming, what does encapsulation primarily refer to?', 'OOPs'),
('Which SQL command is mainly used to retrieve data from a table?', 'DBMS'),
('What is the primary role of the JVM in Java?', 'Java'),
('Which protocol is commonly used for secure web browsing?', 'Computer Networks'),
('Supervised learning models are trained mainly using what type of data?', 'Machine Learning'),
('Which data structure follows the FIFO principle?', 'Data Structures'),
('What does DBMS stand for?', 'DBMS'),
('In prompt engineering, what is role prompting?', 'Prompt Engineering'),
('What is phishing?', 'Cyber Security'),
('Which Git command is used to upload local commits to a remote repository?', 'Version Control'),
('In Java, what is one common use of the final keyword?', 'Java'),
('What does AI hallucination usually mean?', 'AI Literacy'),
('Which normal form is mainly concerned with removing partial dependency?', 'DBMS'),
('What is the default port number for HTTPS?', 'Computer Networks'),
('Which loop in Java is guaranteed to execute at least once?', 'Java'),
('Which of the following is commonly used for classification problems?', 'Machine Learning'),
('What does CPU stand for?', 'Computer Basics'),
('What is MFA in cyber security?', 'Cyber Security'),
('Which SQL join returns only the rows that have matching values in both tables?', 'DBMS'),
('What is the main purpose of DNS?', 'Computer Networks'),
('In OOP, inheritance allows a class to do what?', 'OOPs'),
('In large language models, a token is best described as what?', 'Prompt Engineering'),
('Which Java collection does not allow duplicate elements?', 'Java Collections'),
('What does API stand for?', 'Software Engineering'),
('Which chart is commonly used to show parts of a whole?', 'Data Science'),
('What does overfitting in machine learning usually mean?', 'Machine Learning'),
('What is ransomware?', 'Cyber Security'),
('Which command line tool is commonly used to test whether another host is reachable on a network?', 'Computer Networks'),
('A foreign key in a database is mainly used to maintain what?', 'DBMS'),
('Which Java concept makes the language platform independent?', 'Java'),
('Cloud computing mainly provides what to users?', 'Cloud Computing'),
('Which prompting technique asks the AI to solve a task in smaller ordered steps?', 'Prompt Engineering'),
('What is one-hot encoding mainly used for?', 'Data Science'),
('Which attack attempts to overwhelm a server with huge amounts of traffic?', 'Cyber Security'),
('What is the extension of a compiled Java bytecode file?', 'Java'),
('Which SQL clause is used to filter grouped results?', 'DBMS'),
('What is Unicode?', 'Computer Basics'),
('Which machine learning task predicts a continuous numeric value?', 'Machine Learning'),
('What does a VPN mainly do?', 'Cyber Security'),
('Data cleaning is mainly done to achieve what?', 'Data Science'),
('Which block in Java exception handling usually executes whether an exception occurs or not?', 'Java'),
('Which HTML tag defines the largest heading by default?', 'Web Basics'),
('In AI usage, what is a prompt?', 'AI Literacy'),
('What is the binary representation of decimal number 10?', 'Computer Science'),
('Which of the following storage devices is generally the fastest?', 'Computer Hardware'),
('SQL injection mainly exploits what kind of weakness?', 'Cyber Security'),
('Which Java interface is commonly used to define a task that can run on a thread?', 'Java'),
('Generative AI tools are mainly known for which capability?', 'Current Technical Affairs'),
('What is the main purpose of creating an index on a frequently searched database column?', 'DBMS'),
('Which HTTP method is commonly used to update an existing resource?', 'Web & APIs');

INSERT INTO options (question_id, option_label, option_text, is_correct) VALUES
(1, 'A', 'Bundling data and methods inside a class and controlling access', TRUE),
(1, 'B', 'Splitting one class into many unrelated files', FALSE),
(1, 'C', 'Running multiple programs at the same time', FALSE),
(1, 'D', 'Converting source code directly into machine code', FALSE),
(2, 'A', 'UPDATE', FALSE),
(2, 'B', 'SELECT', TRUE),
(2, 'C', 'DELETE', FALSE),
(2, 'D', 'ALTER', FALSE),
(3, 'A', 'To design the user interface', FALSE),
(3, 'B', 'To store Java source files', FALSE),
(3, 'C', 'To run Java bytecode on different platforms', TRUE),
(3, 'D', 'To replace the Java compiler', FALSE),
(4, 'A', 'FTP', FALSE),
(4, 'B', 'HTTP', FALSE),
(4, 'C', 'SMTP', FALSE),
(4, 'D', 'HTTPS', TRUE),
(5, 'A', 'Labeled data', TRUE),
(5, 'B', 'Encrypted data', FALSE),
(5, 'C', 'Only image data', FALSE),
(5, 'D', 'Random data with no pattern', FALSE),
(6, 'A', 'Stack', FALSE),
(6, 'B', 'Queue', TRUE),
(6, 'C', 'Tree', FALSE),
(6, 'D', 'Graph', FALSE),
(7, 'A', 'Digital Backup Management Service', FALSE),
(7, 'B', 'Distributed Binary Memory System', FALSE),
(7, 'C', 'Database Management System', TRUE),
(7, 'D', 'Data Business Mapping Solution', FALSE),
(8, 'A', 'Telling the AI which role or persona to act as', TRUE),
(8, 'B', 'Changing the computer user account', FALSE),
(8, 'C', 'Training a neural network from scratch', FALSE),
(8, 'D', 'Deleting previous prompts permanently', FALSE),
(9, 'A', 'A method for cooling data centers', FALSE),
(9, 'B', 'A way to compress files into smaller size', FALSE),
(9, 'C', 'A browser feature for private browsing', FALSE),
(9, 'D', 'A fraudulent attempt to steal sensitive information', TRUE),
(10, 'A', 'git clone', FALSE),
(10, 'B', 'git merge', FALSE),
(10, 'C', 'git push', TRUE),
(10, 'D', 'git init', FALSE),
(11, 'A', 'To create a database table', FALSE),
(11, 'B', 'To prevent a method from being overridden', TRUE),
(11, 'C', 'To convert code into bytecode', FALSE),
(11, 'D', 'To enable multiple inheritance', FALSE),
(12, 'A', 'The model generates convincing but incorrect information', TRUE),
(12, 'B', 'The monitor screen flickers while using AI', FALSE),
(12, 'C', 'The AI system stops using electricity', FALSE),
(12, 'D', 'The dataset becomes smaller after training', FALSE),
(13, 'A', 'First Normal Form', FALSE),
(13, 'B', 'Second Normal Form', TRUE),
(13, 'C', 'Boyce-Codd Normal Form', FALSE),
(13, 'D', 'Fifth Normal Form', FALSE),
(14, 'A', '21', FALSE),
(14, 'B', '80', FALSE),
(14, 'C', '443', TRUE),
(14, 'D', '8080', FALSE),
(15, 'A', 'for loop', FALSE),
(15, 'B', 'while loop', FALSE),
(15, 'C', 'enhanced for loop', FALSE),
(15, 'D', 'do-while loop', TRUE),
(16, 'A', 'Logistic Regression', TRUE),
(16, 'B', 'Linear Interpolation', FALSE),
(16, 'C', 'Bubble Sort', FALSE),
(16, 'D', 'Quick Union', FALSE),
(17, 'A', 'Central Process Utility', FALSE),
(17, 'B', 'Central Processing Unit', TRUE),
(17, 'C', 'Computer Performance Unit', FALSE),
(17, 'D', 'Control Program Unit', FALSE),
(18, 'A', 'Managed Firewall Access', FALSE),
(18, 'B', 'Machine Function Architecture', FALSE),
(18, 'C', 'Multi-Factor Authentication', TRUE),
(18, 'D', 'Mainframe File Allocation', FALSE),
(19, 'A', 'INNER JOIN', TRUE),
(19, 'B', 'LEFT JOIN', FALSE),
(19, 'C', 'RIGHT JOIN', FALSE),
(19, 'D', 'FULL TEXT JOIN', FALSE),
(20, 'A', 'To compress video files', FALSE),
(20, 'B', 'To design web pages', FALSE),
(20, 'C', 'To store passwords securely', FALSE),
(20, 'D', 'To translate domain names into IP addresses', TRUE),
(21, 'A', 'Run faster than all other classes', FALSE),
(21, 'B', 'Acquire properties and behavior from another class', TRUE),
(21, 'C', 'Connect directly to the internet', FALSE),
(21, 'D', 'Prevent object creation completely', FALSE),
(22, 'A', 'A hardware chip used in AI servers', FALSE),
(22, 'B', 'A special type of database row', FALSE),
(22, 'C', 'A small unit of text processed by the model', TRUE),
(22, 'D', 'A password reset code', FALSE),
(23, 'A', 'Set', TRUE),
(23, 'B', 'List', FALSE),
(23, 'C', 'Array', FALSE),
(23, 'D', 'StringBuilder', FALSE),
(24, 'A', 'Application Program Internet', FALSE),
(24, 'B', 'Advanced Processing Interface', FALSE),
(24, 'C', 'Automated Protocol Integration', FALSE),
(24, 'D', 'Application Programming Interface', TRUE),
(25, 'A', 'Scatter plot', FALSE),
(25, 'B', 'Pie chart', TRUE),
(25, 'C', 'Histogram', FALSE),
(25, 'D', 'Line chart', FALSE),
(26, 'A', 'The model learns the training data too closely and performs poorly on new data', TRUE),
(26, 'B', 'The model takes too little memory', FALSE),
(26, 'C', 'The model is too simple to learn patterns', FALSE),
(26, 'D', 'The dataset has no labels', FALSE),
(27, 'A', 'A tool used to increase internet speed', FALSE),
(27, 'B', 'A backup strategy for email servers', FALSE),
(27, 'C', 'Malware that encrypts files and demands payment', TRUE),
(27, 'D', 'A harmless popup advertisement', FALSE),
(28, 'A', 'mkdir', FALSE),
(28, 'B', 'copy', FALSE),
(28, 'C', 'format', FALSE),
(28, 'D', 'ping', TRUE),
(29, 'A', 'Screen resolution', FALSE),
(29, 'B', 'Referential integrity', TRUE),
(29, 'C', 'CPU clock speed', FALSE),
(29, 'D', 'File compression ratio', FALSE),
(30, 'A', 'It only runs on Windows', FALSE),
(30, 'B', 'It is always compiled into native machine code', FALSE),
(30, 'C', 'Java bytecode runs on a JVM available for many platforms', TRUE),
(30, 'D', 'Java avoids using memory', FALSE),
(31, 'A', 'On-demand access to computing resources over the internet', TRUE),
(31, 'B', 'Only physical keyboards and monitors', FALSE),
(31, 'C', 'A guarantee that software will never fail', FALSE),
(31, 'D', 'Offline-only storage with no networking', FALSE),
(32, 'A', 'Random prompting', FALSE),
(32, 'B', 'Step-by-step prompting', TRUE),
(32, 'C', 'Silent prompting', FALSE),
(32, 'D', 'Binary prompting', FALSE),
(33, 'A', 'Encrypting image files', FALSE),
(33, 'B', 'Reducing CPU temperature', FALSE),
(33, 'C', 'Converting decimal values to fractions', FALSE),
(33, 'D', 'Representing categorical values as binary columns', TRUE),
(34, 'A', 'DDoS attack', TRUE),
(34, 'B', 'Code refactoring', FALSE),
(34, 'C', 'Normalization', FALSE),
(34, 'D', 'Data annotation', FALSE),
(35, 'A', '.java', FALSE),
(35, 'B', '.jarx', FALSE),
(35, 'C', '.class', TRUE),
(35, 'D', '.src', FALSE),
(36, 'A', 'ORDER BY', FALSE),
(36, 'B', 'WHERE', FALSE),
(36, 'C', 'LIMIT', FALSE),
(36, 'D', 'HAVING', TRUE),
(37, 'A', 'A type of antivirus software', FALSE),
(37, 'B', 'A character encoding standard for text', TRUE),
(37, 'C', 'A computer motherboard slot', FALSE),
(37, 'D', 'A programming language only for AI', FALSE),
(38, 'A', 'Regression', TRUE),
(38, 'B', 'Classification', FALSE),
(38, 'C', 'Clustering only', FALSE),
(38, 'D', 'Tokenization', FALSE),
(39, 'A', 'Repairs damaged hard drives', FALSE),
(39, 'B', 'Deletes browser history permanently', FALSE),
(39, 'C', 'Creates an encrypted tunnel for network traffic', TRUE),
(39, 'D', 'Converts source code into bytecode', FALSE),
(40, 'A', 'Increase monitor brightness', FALSE),
(40, 'B', 'Replace all numbers with words', FALSE),
(40, 'C', 'Delete all rows from a dataset', FALSE),
(40, 'D', 'Remove errors, duplicates, and inconsistencies from data', TRUE),
(41, 'A', 'catch', FALSE),
(41, 'B', 'finally', TRUE),
(41, 'C', 'throw', FALSE),
(41, 'D', 'extends', FALSE),
(42, 'A', '<h1>', TRUE),
(42, 'B', '<head>', FALSE),
(42, 'C', '<p>', FALSE),
(42, 'D', '<title>', FALSE),
(43, 'A', 'A hardware sensor inside the CPU', FALSE),
(43, 'B', 'An encrypted backup file', FALSE),
(43, 'C', 'The instruction or input given to the model', TRUE),
(43, 'D', 'A type of network router', FALSE),
(44, 'A', '1001', FALSE),
(44, 'B', '1111', FALSE),
(44, 'C', '1100', FALSE),
(44, 'D', '1010', TRUE),
(45, 'A', 'HDD', FALSE),
(45, 'B', 'NVMe SSD', TRUE),
(45, 'C', 'DVD', FALSE),
(45, 'D', 'USB 2.0 flash drive', FALSE),
(46, 'A', 'Unsafe handling of user input in database queries', TRUE),
(46, 'B', 'Low monitor resolution', FALSE),
(46, 'C', 'Weak Wi-Fi signal only', FALSE),
(46, 'D', 'Too many CSS files', FALSE),
(47, 'A', 'Serializable', FALSE),
(47, 'B', 'Comparable', FALSE),
(47, 'C', 'Runnable', TRUE),
(47, 'D', 'Cloneable', FALSE),
(48, 'A', 'Manufacturing computer chips physically', FALSE),
(48, 'B', 'Cooling cloud servers with less energy', FALSE),
(48, 'C', 'Replacing every database automatically', FALSE),
(48, 'D', 'Creating new content such as text, images, audio, or code', TRUE),
(49, 'A', 'To reduce monitor size', FALSE),
(49, 'B', 'To speed up data retrieval', TRUE),
(49, 'C', 'To convert SQL into Java', FALSE),
(49, 'D', 'To prevent backups from running', FALSE),
(50, 'A', 'GET', FALSE),
(50, 'B', 'HEAD', FALSE),
(50, 'C', 'PUT', TRUE),
(50, 'D', 'TRACE', FALSE);

CREATE INDEX idx_questions_category ON questions(category);
CREATE INDEX idx_interactions_session_id ON user_interactions(session_id);
CREATE INDEX idx_interactions_user_id ON user_interactions(user_id);
CREATE INDEX idx_options_question_id ON options(question_id);